### ISSUE TITLE
General issues

### ISSUE THREAD

**Issue by YannickWllms** [gerardsyd/portfolio_tracker#2]
The home function in the routing of the index (_@app.route('/') def home()_ ) gave an error ('Please provide at least one ticker'). I uncommented the code _return render_template_ and deleted the _return updatepf()_; now it's working (I get to see the homepage on localhost:5000). So the code looks like this:

@app.route('/')
def home():
    return render_template('home.jinja2', title="Portfolio Tracker: Home")

There's a second issue now, whenever I press 'add all' on the /add_trades page (after adding TSLA or AAPL for example), it gives me an error '_[Errno 2] No such file or directory: 'data/pf_trades.pkl_' which is generated by executing the code on line 112 (_pf.trades_df.to_pickle(TRADES_FILE)_). Any idea how to solve this?

**Comment by gerardsyd** [comment]
Hi Yannick, are you using the master branch or the dev branch?
I'll check re: no file or directory. I thought I had caught that error and dealt with it.

**Comment by YannickWllms** [comment]
Gerard,

I am not very familiar with Github (used it only a few years back on a data science course), so I just DL’ed the code as zip file. Looks like this is the master branch, will try now with the dev branch (which you updated most recently).

Sorry for the hassle, and thank you for your quick reactions.

Best regards,

On 9 Dec 2020, at 22:37, Gerard <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Yannick, are you using the master branch or the dev branch?
I'll check re: no file or directory. I thought I had caught that error and dealt with it.

**Comment by gerardsyd** [comment]
All good. The dev branch is probably more complex and it connects with SQL
so might be harder to get working. I'll be able to look at your issue a bit
later today and will update you.


---

Gerard Pais
gerard.pais@gmail.com
+61 422 101 872

**Comment by gerardsyd** [comment]
Hi Yannick, I have fixed issue 1 (ValueError) in the new app.py file under master. If you re-download this and run, it should work fine. 
With issue 2, you need to create two additional folders under the main folder called logs and data. I thought GH would upload the folder structure but it doesn't seem to have done so. I've updated the README

**Comment by YannickWllms** [comment]
Hi Gerard,

Thanks for fixing, I got it working now. Found a few more ‘bugs’ (don’t know if you’re interested to further develop, but came across them so thought it would only be logic to share):

- When I add trades (for example AAPL and TSLA), the cost base seems to be referring to the 1st trade for both of them. Adding more trades will all refer to cost base of first added trade
- Why trying to edit trade, got an internal error (ValueError: style is not supported for non-unique indices., attached a screen shot).
- Changing currency doesn’t seem to change anything. Based on the current value of the stocks I see the default is USD?


Just as an idea for future version (I had this with my excel spreadsheet before), it might be useful to also compare the stock performance versus a popular stock index (S&P, DJI, NASDAQ) in order to see which stocks are lagging behind.

You made me pick-up programming again (not that I ever wrote code as you did, but I could do basic stuff and read/figure out more complex code made by others) by starting with a refresher course of Python and hopefully I’m quickly up to speed and can even contribute, who knows. Thanks for that!


Best regards,

Yannick Willems



On 10 Dec 2020, at 04:21, Gerard <notifications@github.com<mailto:notifications@github.com>> wrote:



Closed #2<https://github.com/gerardsyd/portfolio_tracker/issues/2>.

**Comment by gerardsyd** [comment]
Hi Yannick,

I'm developing the dev version which is a bit of a move away from the original in that it can handle multiple users and be a website by itself. Very happy to collaborate as not sure where I'll end up taking it. I would like to host it somewhere eventually. 

For the first bug, could you add some screenshots or upload the CSV of trades you used? I'm not sure I quite understand what is happening and difficult to work out the bug without seeing the data. 
I can't see the screenshot but that error is related to the display of the dataframe via the webapp. This should be fixed in the dev version (but like I mentioned, that version requires a mySQL database and some additional config so depends if you have interest in going down that route). 
Yes, currency in that version doesn't do anything. It's on my to-do list but I haven't found an elegant solution for it as yet. My use case doesn't need currency so it hasn't been a focus. By default, it will use the base currency of the stock.
Noted re: idea of comparing against index. I'll add that to my feature list. The table is getting a bit crowded though so any ideas on UX would be great!
Always open to help with coding. This is very far from my day job and really just a hobby project for me. I haven't done any real dev for the last few weeks as work's been busy but I'll get back into it over xmas and ny when things slow down. 
Cheers,
Gerard

**Comment by gerardsyd** [comment]
If you're interested, I've deployed a website here: 
www.pftrackr.com
It has a few kinks but it should work for the most part. Be awesome to get some feedback.

**Comment by YannickWllms** [comment]
Gerard,

Sorry didn’t have time yet to reply to your previous e-mail. I’ll check the website and let you know if there are any bugs or points of improvement.

Regards,

Yannick

Sent from my iPhone

On 16 Dec 2020, at 13:40, Gerard <notifications@github.com> wrote:

﻿

If you're interested, I've deployed a website here:
www.pftrackr.com<http://www.pftrackr.com>
It has a few kinks but it should work for the most part. Be awesome to get some feedback.
