### ISSUE TITLE
Cost calculation incorrect

### ISSUE THREAD

**Issue by g00dchristian** [gerardsyd/portfolio_tracker#3]
**Describe the bug**
The cost calculation for each asset is incorrect resulting in the subsequent calculations to be incorrect. 

**To Reproduce**
I cleared and re-cloned the repo yet still encountered the same issue.
1. Install repo
2. Click on 'Load Portfolio'
3. Load this file: [My Trades](https://drive.google.com/file/d/1b0JVtJwG1DpSDr6g5j-4FLXaNsRH9ivP/view?usp=sharing)

**Screenshots**
See 'Cost' Column
![Capture](https://user-images.githubusercontent.com/40678349/102428575-70e79880-4066-11eb-93aa-5b814b6875c3.PNG)

**Desktop (please complete the following information):**
 - OS: Win10 19041.685
 - Browser: Chrome
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by gerardsyd** [comment]
Hmm, thanks. I can replicate the error. Seems to be an issue when there are single trades. I remember having this issue earlier and I thought I had it solved. Let me debug. 
FYI, I am running a version of the dev here: https://pftrackr.com/ if you want to try it. I just checked and this bug is still in that version as well. Working on it!
I haven't fully implemented the load from CSV in the dev version so I'll look at that too.

**Comment by gerardsyd** [comment]
Hi, could you tell me which version of pandas you are using?
Also feel free to try pftrackr.com which is running the dev version of the project. I'm still working on the CSV import but otherwise it should all work. 
Thanks!

**Comment by gerardsyd** [comment]
Hi - I am closing this as I haven't heard back. 
Thanks
